import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery } from "@apollo/client";
import { getCategories } from "./category/services/graphql/schema";
import Link from "next/link";

export default function Home() {
  const response = useQuery(getCategories);
  const { loading, error, data } = response;

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Categories</h1>

        <ul>
          {data && data.categories.items.length > 0 ? (
            data.categories.items.map((category) => (
              <li key={category.id}>
                {category.image !== null ? (
                  <Image
                    src={category.image}
                    alt={category.name}
                    width={150}
                    height={75}
                  />
                ) : (
                  <></>
                )}
                <Link
                  href={{
                    pathname: `/category/${category.id}`,
                  }}
                  as={`/category/${category.id}`}
                >
                  <a style={{ color: "blue" }}>{category.name}</a>
                </Link>
              </li>
            ))
          ) : (
            <p>No categories found</p>
          )}
        </ul>
      </main>
    </div>
  );
}
